apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          {{- range .Values.paths }}
          - path: {{ .path }}
            pathType: "Prefix"
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: 80
          {{- end }}
