name: Golang

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up 
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: BuildAPI
      run: cd backend/api && go build -o bin/main && cd ../..
    - name: BuildAUTH
      run: cd backend/auth && go build -o bin/main && cd ../..

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 3m
